<#@ template hostspecific="false" language="C#" #>
<#@ output extension=".cs" #>
// <auto-generated />
#pragma warning disable

namespace T4.SourceGenerator.Example;

public static class Squares
{
<#
	for (var i = 0; i < 256; i++)
	{
#>
   public const int Squared<#= i #> = <#= i * i #>;
<#
}
#>
}
